/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import loja.*;

/**
 *
 * @author slo
 */
public class GUISistema extends javax.swing.JFrame {

    private BancoVendas Banco_Vendas;
    private BancoClientes Banco_Clientes;
    private Estoque Estoque;
    public GUISistema() {
        initComponents();
        Banco_Vendas = new BancoVendas();
        Banco_Clientes = new BancoClientes();
        Estoque = new Estoque();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField27 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneCliente = new javax.swing.JTabbedPane();
        jPanelClienteCadastrar = new javax.swing.JPanel();
        jLabelCadastroClienteNome = new javax.swing.JLabel();
        jTextFieldClienteCadastrarNome = new javax.swing.JTextField();
        jLabelCadastroClienteCodigo = new javax.swing.JLabel();
        jTextFieldClienteCadastrarCodigo = new javax.swing.JTextField();
        jLabelCadastroClienteCPF = new javax.swing.JLabel();
        jTextFieldClienteCadastrarCPF = new javax.swing.JTextField();
        jLabelCadastroClienteEmail = new javax.swing.JLabel();
        jTextFieldClienteCadastrarEmail = new javax.swing.JTextField();
        jLabelCadastroClienteSenha = new javax.swing.JLabel();
        jPasswordFieldCadastrarSenha = new javax.swing.JPasswordField();
        jLabelCadastroClienteEndereco1 = new javax.swing.JLabel();
        jTextFieldClienteCadastrarEndereco1 = new javax.swing.JTextField();
        jLabelCadastroClienteEnderecoOpcional = new javax.swing.JLabel();
        jLabelCadastroClienteEndereco2 = new javax.swing.JLabel();
        jTextFieldClienteCadastrarEndereco2 = new javax.swing.JTextField();
        jLabelCadastroClienteEndereco3 = new javax.swing.JLabel();
        jTextFieldClienteCadastrarEndereco3 = new javax.swing.JTextField();
        jButtonClienteCadastrar = new javax.swing.JButton();
        jPanelClienteAlterar = new javax.swing.JPanel();
        jLabelClienteAlterarCodigo = new javax.swing.JLabel();
        jTextFieldClienteAlterarCodigo = new javax.swing.JTextField();
        jLabelClienteAlterarNome = new javax.swing.JLabel();
        jTextFieldClienteAlterarNome = new javax.swing.JTextField();
        jLabelClienteAlterarCPF = new javax.swing.JLabel();
        jLabelClienteAlterarEmail = new javax.swing.JLabel();
        jLabelClienteAlterarEndereco = new javax.swing.JLabel();
        jLabelClienteAlterarSenha = new javax.swing.JLabel();
        jTextFieldClienteAlterarCPF = new javax.swing.JTextField();
        jTextFieldClienteAlterarEmail = new javax.swing.JTextField();
        jTextFieldClienteAlterarEndereco = new javax.swing.JTextField();
        jPasswordFieldClienteAlterarSenha = new javax.swing.JPasswordField();
        jButtonClienteAlterar = new javax.swing.JButton();
        jPanelClienteListar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPaneProduto = new javax.swing.JTabbedPane();
        jPanelProdutoCadastrar = new javax.swing.JPanel();
        jLabelProdutoCadastrarCodigo = new javax.swing.JLabel();
        jTextFieldProdutoCadastrarCodigo = new javax.swing.JTextField();
        jLabelProdutoCadastrarQuantidade = new javax.swing.JLabel();
        jTextFieldProdutoCadastrarQuantidade = new javax.swing.JTextField();
        jLabelProdutoCadastrarPreco = new javax.swing.JLabel();
        jTextFieldProdutoCadastrarPreco = new javax.swing.JTextField();
        jLabelProdutoCadastrarDescricao = new javax.swing.JLabel();
        jLabelProdutoCadastrarCategoria = new javax.swing.JLabel();
        jTextFieldProdutoCadastrarCategoria = new javax.swing.JTextField();
        jLabelProdutoCadastrarParticularidade = new javax.swing.JLabel();
        jTextFieldProdutoCadastrarParticularidade = new javax.swing.JTextField();
        jButtonProdutoCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaProdutoCadastrarDescricao = new javax.swing.JTextArea();
        jPanelProdutoAlterar = new javax.swing.JPanel();
        jLabelProdutoAlterarCodigo = new javax.swing.JLabel();
        jTextFieldProdutoAlteraCodigor = new javax.swing.JTextField();
        jLabelProdutoAlterarQuantidade = new javax.swing.JLabel();
        jTextFieldProdutoAlterarQuantidade = new javax.swing.JTextField();
        jLabelProdutoAlterarPreco = new javax.swing.JLabel();
        jTextFieldProdutoAlterarPreco = new javax.swing.JTextField();
        jLabelProdutoAlterarCategoria = new javax.swing.JLabel();
        jLabelProdutoAlterarParticularidade = new javax.swing.JLabel();
        jLabelProdutoAlterarDescricao = new javax.swing.JLabel();
        jTextFieldProdutoAlterarCategoria = new javax.swing.JTextField();
        jTextFieldProdutoAlterarParticularidade = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaProdutoAlterarDescricao = new javax.swing.JTextArea();
        jButtonProdutoAlterar = new javax.swing.JButton();
        jPanelProdutoListar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPaneVendas = new javax.swing.JTabbedPane();
        jPanelVendasNova = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanelVendasAlterar = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanelVendasListar = new javax.swing.JPanel();

        jTextField27.setText("jTextField27");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema da Loja");

        jLabelCadastroClienteNome.setText("Nome:");

        jTextFieldClienteCadastrarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteCadastrarNomeActionPerformed(evt);
            }
        });

        jLabelCadastroClienteCodigo.setText("Código:");

        jLabelCadastroClienteCPF.setText("CPF:");

        jLabelCadastroClienteEmail.setText("E-Mail:");

        jLabelCadastroClienteSenha.setText("Senha:");

        jLabelCadastroClienteEndereco1.setText("Endereço:");

        jLabelCadastroClienteEnderecoOpcional.setText("Endereços Adicionais(Opcional)");

        jLabelCadastroClienteEndereco2.setText("Endereço:");

        jLabelCadastroClienteEndereco3.setText("Endereço:");

        jButtonClienteCadastrar.setText("Cadastrar");
        jButtonClienteCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClienteCadastrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelClienteCadastrarLayout = new javax.swing.GroupLayout(jPanelClienteCadastrar);
        jPanelClienteCadastrar.setLayout(jPanelClienteCadastrarLayout);
        jPanelClienteCadastrarLayout.setHorizontalGroup(
            jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                            .addComponent(jLabelCadastroClienteEndereco1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldClienteCadastrarEndereco1))
                        .addComponent(jLabelCadastroClienteEnderecoOpcional)
                        .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                            .addComponent(jLabelCadastroClienteEndereco2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldClienteCadastrarEndereco2))
                        .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                            .addComponent(jLabelCadastroClienteEndereco3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldClienteCadastrarEndereco3))
                        .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                            .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelClienteCadastrarLayout.createSequentialGroup()
                                    .addComponent(jLabelCadastroClienteSenha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPasswordFieldCadastrarSenha))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelClienteCadastrarLayout.createSequentialGroup()
                                    .addComponent(jLabelCadastroClienteCPF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldClienteCadastrarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelCadastroClienteEmail)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldClienteCadastrarEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                        .addComponent(jLabelCadastroClienteNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldClienteCadastrarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCadastroClienteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldClienteCadastrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteCadastrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClienteCadastrar)
                .addContainerGap())
        );
        jPanelClienteCadastrarLayout.setVerticalGroup(
            jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroClienteNome)
                    .addComponent(jTextFieldClienteCadastrarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroClienteCodigo)
                    .addComponent(jTextFieldClienteCadastrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroClienteCPF)
                    .addComponent(jTextFieldClienteCadastrarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroClienteEmail)
                    .addComponent(jTextFieldClienteCadastrarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroClienteSenha)
                    .addComponent(jPasswordFieldCadastrarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroClienteEndereco1)
                    .addComponent(jTextFieldClienteCadastrarEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCadastroClienteEnderecoOpcional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroClienteEndereco2)
                    .addComponent(jTextFieldClienteCadastrarEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroClienteEndereco3)
                    .addComponent(jTextFieldClienteCadastrarEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButtonClienteCadastrar)
                .addContainerGap())
        );

        jTabbedPaneCliente.addTab("Cadastrar Cliente", jPanelClienteCadastrar);

        jLabelClienteAlterarCodigo.setText("Código:");

        jTextFieldClienteAlterarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteAlterarCodigoActionPerformed(evt);
            }
        });

        jLabelClienteAlterarNome.setText("Novo nome:");

        jLabelClienteAlterarCPF.setText("Novo CPF:");

        jLabelClienteAlterarEmail.setText("Novo e-mail:");

        jLabelClienteAlterarEndereco.setText("Novo endereço:");

        jLabelClienteAlterarSenha.setText("Nova senha:");

        jPasswordFieldClienteAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldClienteAlterarSenhaActionPerformed(evt);
            }
        });

        jButtonClienteAlterar.setText("Salvar Alterações");
        jButtonClienteAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClienteAlterarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelClienteAlterarLayout = new javax.swing.GroupLayout(jPanelClienteAlterar);
        jPanelClienteAlterar.setLayout(jPanelClienteAlterarLayout);
        jPanelClienteAlterarLayout.setHorizontalGroup(
            jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelClienteAlterarCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldClienteAlterarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelClienteAlterarNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldClienteAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelClienteAlterarCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldClienteAlterarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelClienteAlterarEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldClienteAlterarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelClienteAlterarSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldClienteAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelClienteAlterarEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldClienteAlterarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteAlterarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClienteAlterar)
                .addContainerGap())
        );
        jPanelClienteAlterarLayout.setVerticalGroup(
            jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteAlterarCodigo)
                    .addComponent(jTextFieldClienteAlterarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteAlterarNome)
                    .addComponent(jTextFieldClienteAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteAlterarCPF)
                    .addComponent(jTextFieldClienteAlterarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteAlterarEmail)
                    .addComponent(jTextFieldClienteAlterarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteAlterarSenha)
                    .addComponent(jPasswordFieldClienteAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteAlterarEndereco)
                    .addComponent(jTextFieldClienteAlterarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButtonClienteAlterar)
                .addContainerGap())
        );

        jTabbedPaneCliente.addTab("Alterar Cadastro", jPanelClienteAlterar);

        javax.swing.GroupLayout jPanelClienteListarLayout = new javax.swing.GroupLayout(jPanelClienteListar);
        jPanelClienteListar.setLayout(jPanelClienteListarLayout);
        jPanelClienteListarLayout.setHorizontalGroup(
            jPanelClienteListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        jPanelClienteListarLayout.setVerticalGroup(
            jPanelClienteListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        jTabbedPaneCliente.addTab("Listar Clientes", jPanelClienteListar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCliente)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCliente)
        );

        jTabbedPane1.addTab("Cliente", jPanel1);

        jLabelProdutoCadastrarCodigo.setText("Código:");

        jLabelProdutoCadastrarQuantidade.setText("Quantidade:");

        jTextFieldProdutoCadastrarQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoCadastrarQuantidadeActionPerformed(evt);
            }
        });

        jLabelProdutoCadastrarPreco.setText("Preço unitário:");

        jTextFieldProdutoCadastrarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoCadastrarPrecoActionPerformed(evt);
            }
        });

        jLabelProdutoCadastrarDescricao.setText("Descrição:");

        jLabelProdutoCadastrarCategoria.setText("Categoria:");

        jLabelProdutoCadastrarParticularidade.setText("Particularidade:");

        jButtonProdutoCadastrar.setText("Cadastrar");
        jButtonProdutoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoCadastrarActionPerformed(evt);
            }
        });

        jTextAreaProdutoCadastrarDescricao.setColumns(20);
        jTextAreaProdutoCadastrarDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaProdutoCadastrarDescricao);

        javax.swing.GroupLayout jPanelProdutoCadastrarLayout = new javax.swing.GroupLayout(jPanelProdutoCadastrar);
        jPanelProdutoCadastrar.setLayout(jPanelProdutoCadastrarLayout);
        jPanelProdutoCadastrarLayout.setHorizontalGroup(
            jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutoCadastrarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonProdutoCadastrar))
                    .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                        .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoCadastrarParticularidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoCadastrarParticularidade, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoCadastrarCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoCadastrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelProdutoCadastrarQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoCadastrarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoCadastrarCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoCadastrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoCadastrarPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoCadastrarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoCadastrarDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 162, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelProdutoCadastrarLayout.setVerticalGroup(
            jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoCadastrarCodigo)
                    .addComponent(jTextFieldProdutoCadastrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProdutoCadastrarQuantidade)
                    .addComponent(jTextFieldProdutoCadastrarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoCadastrarPreco)
                    .addComponent(jTextFieldProdutoCadastrarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoCadastrarCategoria)
                    .addComponent(jTextFieldProdutoCadastrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoCadastrarParticularidade)
                    .addComponent(jTextFieldProdutoCadastrarParticularidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProdutoCadastrarDescricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButtonProdutoCadastrar)
                .addContainerGap())
        );

        jTabbedPaneProduto.addTab("Cadastrar Produto", jPanelProdutoCadastrar);

        jLabelProdutoAlterarCodigo.setText("Código:");

        jLabelProdutoAlterarQuantidade.setText("Nova quantidade:");

        jLabelProdutoAlterarPreco.setText("Novo Preço:");

        jLabelProdutoAlterarCategoria.setText("Nova Categoria:");

        jLabelProdutoAlterarParticularidade.setText("Nova Particularidade:");

        jLabelProdutoAlterarDescricao.setText("Nova Descrição:");

        jTextAreaProdutoAlterarDescricao.setColumns(20);
        jTextAreaProdutoAlterarDescricao.setRows(5);
        jScrollPane2.setViewportView(jTextAreaProdutoAlterarDescricao);

        jButtonProdutoAlterar.setText("Salvar alterações");
        jButtonProdutoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProdutoAlterarLayout = new javax.swing.GroupLayout(jPanelProdutoAlterar);
        jPanelProdutoAlterar.setLayout(jPanelProdutoAlterarLayout);
        jPanelProdutoAlterarLayout.setHorizontalGroup(
            jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutoAlterarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonProdutoAlterar))
                    .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                        .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoAlterarPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoAlterarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoAlterarCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoAlterarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoAlterarDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                                    .addComponent(jLabelProdutoAlterarParticularidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldProdutoAlterarParticularidade))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProdutoAlterarLayout.createSequentialGroup()
                                    .addComponent(jLabelProdutoAlterarCodigo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldProdutoAlteraCodigor, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelProdutoAlterarQuantidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldProdutoAlterarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelProdutoAlterarLayout.setVerticalGroup(
            jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoAlterarCodigo)
                    .addComponent(jTextFieldProdutoAlteraCodigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProdutoAlterarQuantidade)
                    .addComponent(jTextFieldProdutoAlterarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldProdutoAlterarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProdutoAlterarPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoAlterarCategoria)
                    .addComponent(jTextFieldProdutoAlterarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoAlterarParticularidade)
                    .addComponent(jTextFieldProdutoAlterarParticularidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProdutoAlterarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButtonProdutoAlterar)
                .addContainerGap())
        );

        jTabbedPaneProduto.addTab("Alterar Estoque", jPanelProdutoAlterar);

        javax.swing.GroupLayout jPanelProdutoListarLayout = new javax.swing.GroupLayout(jPanelProdutoListar);
        jPanelProdutoListar.setLayout(jPanelProdutoListarLayout);
        jPanelProdutoListarLayout.setHorizontalGroup(
            jPanelProdutoListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        jPanelProdutoListarLayout.setVerticalGroup(
            jPanelProdutoListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        jTabbedPaneProduto.addTab("Listar Produtos", jPanelProdutoListar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneProduto, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneProduto, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Produto", jPanel2);

        jLabel28.setText("Código de venda:");

        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });

        jLabel29.setText("Código do cliente:");

        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });

        jLabel30.setText("Data:");

        jLabel31.setText("Status:");

        jLabel32.setText("Código produto:");

        jLabel33.setText("Quantidade:");

        jButton5.setText("Cadastrar venda");

        javax.swing.GroupLayout jPanelVendasNovaLayout = new javax.swing.GroupLayout(jPanelVendasNova);
        jPanelVendasNova.setLayout(jPanelVendasNovaLayout);
        jPanelVendasNovaLayout.setHorizontalGroup(
            jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendasNovaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
            .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(121, 275, Short.MAX_VALUE))
        );
        jPanelVendasNovaLayout.setVerticalGroup(
            jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jTabbedPaneVendas.addTab("Nova Venda", jPanelVendasNova);

        jLabel34.setText("Código da venda:");

        jLabel35.setText("Novo status:");

        jButton6.setText("Salvar alteração");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVendasAlterarLayout = new javax.swing.GroupLayout(jPanelVendasAlterar);
        jPanelVendasAlterar.setLayout(jPanelVendasAlterarLayout);
        jPanelVendasAlterarLayout.setHorizontalGroup(
            jPanelVendasAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendasAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendasAlterarLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendasAlterarLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(324, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendasAlterarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanelVendasAlterarLayout.setVerticalGroup(
            jPanelVendasAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendasAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendasAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        jTabbedPaneVendas.addTab("Alterar Status de Venda", jPanelVendasAlterar);

        javax.swing.GroupLayout jPanelVendasListarLayout = new javax.swing.GroupLayout(jPanelVendasListar);
        jPanelVendasListar.setLayout(jPanelVendasListarLayout);
        jPanelVendasListarLayout.setHorizontalGroup(
            jPanelVendasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        jPanelVendasListarLayout.setVerticalGroup(
            jPanelVendasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        jTabbedPaneVendas.addTab("Listar Vendas", jPanelVendasListar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVendas)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVendas)
        );

        jTabbedPane1.addTab("Vendas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldClienteAlterarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteAlterarCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteAlterarCodigoActionPerformed

    private void jPasswordFieldClienteAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldClienteAlterarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldClienteAlterarSenhaActionPerformed

    private void jTextFieldClienteCadastrarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteCadastrarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteCadastrarNomeActionPerformed

    private void jTextFieldProdutoCadastrarQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoCadastrarQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoCadastrarQuantidadeActionPerformed

    private void jButtonProdutoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProdutoCadastrarActionPerformed

    private void jTextFieldProdutoCadastrarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoCadastrarPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoCadastrarPrecoActionPerformed

    private void jButtonProdutoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProdutoAlterarActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonClienteAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClienteAlterarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClienteAlterarMouseClicked

    private void jButtonClienteCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClienteCadastrarMouseClicked
       
    }//GEN-LAST:event_jButtonClienteCadastrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonClienteAlterar;
    private javax.swing.JButton jButtonClienteCadastrar;
    private javax.swing.JButton jButtonProdutoAlterar;
    private javax.swing.JButton jButtonProdutoCadastrar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabelCadastroClienteCPF;
    private javax.swing.JLabel jLabelCadastroClienteCodigo;
    private javax.swing.JLabel jLabelCadastroClienteEmail;
    private javax.swing.JLabel jLabelCadastroClienteEndereco1;
    private javax.swing.JLabel jLabelCadastroClienteEndereco2;
    private javax.swing.JLabel jLabelCadastroClienteEndereco3;
    private javax.swing.JLabel jLabelCadastroClienteEnderecoOpcional;
    private javax.swing.JLabel jLabelCadastroClienteNome;
    private javax.swing.JLabel jLabelCadastroClienteSenha;
    private javax.swing.JLabel jLabelClienteAlterarCPF;
    private javax.swing.JLabel jLabelClienteAlterarCodigo;
    private javax.swing.JLabel jLabelClienteAlterarEmail;
    private javax.swing.JLabel jLabelClienteAlterarEndereco;
    private javax.swing.JLabel jLabelClienteAlterarNome;
    private javax.swing.JLabel jLabelClienteAlterarSenha;
    private javax.swing.JLabel jLabelProdutoAlterarCategoria;
    private javax.swing.JLabel jLabelProdutoAlterarCodigo;
    private javax.swing.JLabel jLabelProdutoAlterarDescricao;
    private javax.swing.JLabel jLabelProdutoAlterarParticularidade;
    private javax.swing.JLabel jLabelProdutoAlterarPreco;
    private javax.swing.JLabel jLabelProdutoAlterarQuantidade;
    private javax.swing.JLabel jLabelProdutoCadastrarCategoria;
    private javax.swing.JLabel jLabelProdutoCadastrarCodigo;
    private javax.swing.JLabel jLabelProdutoCadastrarDescricao;
    private javax.swing.JLabel jLabelProdutoCadastrarParticularidade;
    private javax.swing.JLabel jLabelProdutoCadastrarPreco;
    private javax.swing.JLabel jLabelProdutoCadastrarQuantidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelClienteAlterar;
    private javax.swing.JPanel jPanelClienteCadastrar;
    private javax.swing.JPanel jPanelClienteListar;
    private javax.swing.JPanel jPanelProdutoAlterar;
    private javax.swing.JPanel jPanelProdutoCadastrar;
    private javax.swing.JPanel jPanelProdutoListar;
    private javax.swing.JPanel jPanelVendasAlterar;
    private javax.swing.JPanel jPanelVendasListar;
    private javax.swing.JPanel jPanelVendasNova;
    private javax.swing.JPasswordField jPasswordFieldCadastrarSenha;
    private javax.swing.JPasswordField jPasswordFieldClienteAlterarSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPaneCliente;
    private javax.swing.JTabbedPane jTabbedPaneProduto;
    private javax.swing.JTabbedPane jTabbedPaneVendas;
    private javax.swing.JTextArea jTextAreaProdutoAlterarDescricao;
    private javax.swing.JTextArea jTextAreaProdutoCadastrarDescricao;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextFieldClienteAlterarCPF;
    private javax.swing.JTextField jTextFieldClienteAlterarCodigo;
    private javax.swing.JTextField jTextFieldClienteAlterarEmail;
    private javax.swing.JTextField jTextFieldClienteAlterarEndereco;
    private javax.swing.JTextField jTextFieldClienteAlterarNome;
    private javax.swing.JTextField jTextFieldClienteCadastrarCPF;
    private javax.swing.JTextField jTextFieldClienteCadastrarCodigo;
    private javax.swing.JTextField jTextFieldClienteCadastrarEmail;
    private javax.swing.JTextField jTextFieldClienteCadastrarEndereco1;
    private javax.swing.JTextField jTextFieldClienteCadastrarEndereco2;
    private javax.swing.JTextField jTextFieldClienteCadastrarEndereco3;
    private javax.swing.JTextField jTextFieldClienteCadastrarNome;
    private javax.swing.JTextField jTextFieldProdutoAlteraCodigor;
    private javax.swing.JTextField jTextFieldProdutoAlterarCategoria;
    private javax.swing.JTextField jTextFieldProdutoAlterarParticularidade;
    private javax.swing.JTextField jTextFieldProdutoAlterarPreco;
    private javax.swing.JTextField jTextFieldProdutoAlterarQuantidade;
    private javax.swing.JTextField jTextFieldProdutoCadastrarCategoria;
    private javax.swing.JTextField jTextFieldProdutoCadastrarCodigo;
    private javax.swing.JTextField jTextFieldProdutoCadastrarParticularidade;
    private javax.swing.JTextField jTextFieldProdutoCadastrarPreco;
    private javax.swing.JTextField jTextFieldProdutoCadastrarQuantidade;
    // End of variables declaration//GEN-END:variables
}
