/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.awt.FlowLayout;
import java.util.Arrays;
import javax.swing.JDialog;
import javax.swing.JList;
import loja.*;

/**
 *
 * @author slo
 */
public class GUISistema extends javax.swing.JFrame {

    private BancoVendas Banco_Vendas;
    private BancoClientes Banco_Clientes;
    private Estoque Estoque;
    public GUISistema() {
        initComponents();
        Banco_Vendas = new BancoVendas();
        Banco_Clientes = new BancoClientes();
        Estoque = new Estoque();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField27 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneCliente = new javax.swing.JTabbedPane();
        jPanelClienteCadastrar = new javax.swing.JPanel();
        jLabelCadastroClienteNome = new javax.swing.JLabel();
        jTextFieldClienteCadastrarNome = new javax.swing.JTextField();
        jLabelCadastroClienteCodigo = new javax.swing.JLabel();
        jTextFieldClienteCadastrarCodigo = new javax.swing.JTextField();
        jLabelCadastroClienteCPF = new javax.swing.JLabel();
        jTextFieldClienteCadastrarCPF = new javax.swing.JTextField();
        jLabelCadastroClienteEmail = new javax.swing.JLabel();
        jTextFieldClienteCadastrarEmail = new javax.swing.JTextField();
        jLabelCadastroClienteSenha = new javax.swing.JLabel();
        jPasswordFieldCadastrarSenha = new javax.swing.JPasswordField();
        jLabelCadastroClienteEndereco1 = new javax.swing.JLabel();
        jTextFieldClienteCadastrarEndereco1 = new javax.swing.JTextField();
        jLabelCadastroClienteEnderecoOpcional = new javax.swing.JLabel();
        jLabelCadastroClienteEndereco2 = new javax.swing.JLabel();
        jTextFieldClienteCadastrarEndereco2 = new javax.swing.JTextField();
        jLabelCadastroClienteEndereco3 = new javax.swing.JLabel();
        jTextFieldClienteCadastrarEndereco3 = new javax.swing.JTextField();
        jButtonClienteCadastrar = new javax.swing.JButton();
        jPanelClienteAlterar = new javax.swing.JPanel();
        jLabelClienteAlterarCodigo = new javax.swing.JLabel();
        jTextFieldClienteAlterarCodigo = new javax.swing.JTextField();
        jLabelClienteAlterarNome = new javax.swing.JLabel();
        jTextFieldClienteAlterarNome = new javax.swing.JTextField();
        jLabelClienteAlterarCPF = new javax.swing.JLabel();
        jLabelClienteAlterarEmail = new javax.swing.JLabel();
        jLabelClienteAlterarEndereco = new javax.swing.JLabel();
        jLabelClienteAlterarSenha = new javax.swing.JLabel();
        jTextFieldClienteAlterarCPF = new javax.swing.JTextField();
        jTextFieldClienteAlterarEmail = new javax.swing.JTextField();
        jTextFieldClienteAlterarEndereco = new javax.swing.JTextField();
        jPasswordFieldClienteAlterarSenha = new javax.swing.JPasswordField();
        jButtonClienteAlterar = new javax.swing.JButton();
        jLabelClienteAlterarCadastroAviso1 = new javax.swing.JLabel();
        jLabelClienteAlterarCadastroAviso2 = new javax.swing.JLabel();
        jPanelClienteListar = new javax.swing.JPanel();
        jButtonClienteListar = new javax.swing.JButton();
        jScrollPaneListaClientes = new javax.swing.JScrollPane();
        jTextAreaListaClientes = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPaneProduto = new javax.swing.JTabbedPane();
        jPanelProdutoCadastrar = new javax.swing.JPanel();
        jLabelProdutoCadastrarCodigo = new javax.swing.JLabel();
        jTextFieldProdutoCadastrarCodigo = new javax.swing.JTextField();
        jLabelProdutoCadastrarQuantidade = new javax.swing.JLabel();
        jTextFieldProdutoCadastrarQuantidade = new javax.swing.JTextField();
        jLabelProdutoCadastrarPreco = new javax.swing.JLabel();
        jTextFieldProdutoCadastrarPreco = new javax.swing.JTextField();
        jLabelProdutoCadastrarDescricao = new javax.swing.JLabel();
        jLabelProdutoCadastrarCategoria = new javax.swing.JLabel();
        jTextFieldProdutoCadastrarCategoria = new javax.swing.JTextField();
        jLabelProdutoCadastrarParticularidade = new javax.swing.JLabel();
        jTextFieldProdutoCadastrarParticularidade = new javax.swing.JTextField();
        jButtonProdutoCadastrar = new javax.swing.JButton();
        jTextFieldProdutoCadastrarDescricao = new javax.swing.JTextField();
        jPanelProdutoAlterar = new javax.swing.JPanel();
        jLabelProdutoAlterarCodigo = new javax.swing.JLabel();
        jTextFieldProdutoAlterarCodigo = new javax.swing.JTextField();
        jLabelProdutoAlterarQuantidade = new javax.swing.JLabel();
        jTextFieldProdutoAlterarQuantidade = new javax.swing.JTextField();
        jLabelProdutoAlterarPreco = new javax.swing.JLabel();
        jTextFieldProdutoAlterarPreco = new javax.swing.JTextField();
        jLabelProdutoAlterarCategoria = new javax.swing.JLabel();
        jLabelProdutoAlterarParticularidade = new javax.swing.JLabel();
        jLabelProdutoAlterarDescricao = new javax.swing.JLabel();
        jTextFieldProdutoAlterarCategoria = new javax.swing.JTextField();
        jTextFieldProdutoAlterarParticularidade = new javax.swing.JTextField();
        jButtonProdutoAlterar = new javax.swing.JButton();
        jTextFieldProdutoAlterarDescricao = new javax.swing.JTextField();
        jPanelProdutoListar = new javax.swing.JPanel();
        jButton1ListarProdutos = new javax.swing.JButton();
        jScrollPaneListarProdutos = new javax.swing.JScrollPane();
        jTextAreaListarProdutos = new javax.swing.JTextArea();
        jPanelProdutoFiltrar = new javax.swing.JPanel();
        jButtonProdutoFiltrar = new javax.swing.JButton();
        jTextFieldProdutoFiltrar = new javax.swing.JTextField();
        jScrollPaneProdutoFiltrar = new javax.swing.JScrollPane();
        jTextAreaFiltrarProdutos = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPaneVendas = new javax.swing.JTabbedPane();
        jPanelVendasNova = new javax.swing.JPanel();
        jLabelVendaCadastrarCodigoVenda = new javax.swing.JLabel();
        jTextFieldVendasCadastrarCodigoVenda = new javax.swing.JTextField();
        jLabelVendaCadastrarCodigoCliente = new javax.swing.JLabel();
        jTextFieldVendasCadastrarCodigoCliente = new javax.swing.JTextField();
        jLabelVendaCadastrarData = new javax.swing.JLabel();
        jTextFieldVendasCadastrarData = new javax.swing.JFormattedTextField();
        jLabelVendaCadastrarStatus = new javax.swing.JLabel();
        jTextFieldVendasCadastrarStatus = new javax.swing.JTextField();
        jLabelVendaCadastrarCodigoProduto = new javax.swing.JLabel();
        jTextFieldVendasCadastrarCodigoProduto = new javax.swing.JTextField();
        jLabelVendaCadastrarQuantidade = new javax.swing.JLabel();
        jTextFieldVendasCadastrarQuantidade = new javax.swing.JTextField();
        jButtonVendaCadastrar = new javax.swing.JButton();
        jPanelVendasAlterar = new javax.swing.JPanel();
        jLabelVendaAlterarCodigoVenda = new javax.swing.JLabel();
        jTextFieldVendasAlterarCodigoVenda = new javax.swing.JTextField();
        jLabelVendaAlterarStatus = new javax.swing.JLabel();
        jTextFieldVendasAlterarStatus = new javax.swing.JTextField();
        jButtonVendaAlterar = new javax.swing.JButton();
        jPanelVendasListar = new javax.swing.JPanel();
        jButtonListarVendas = new javax.swing.JButton();
        jScrollPaneListarVendas = new javax.swing.JScrollPane();
        jTextAreaListarVendas = new javax.swing.JTextArea();

        jTextField27.setText("jTextField27");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema da Loja");

        jLabelCadastroClienteNome.setText("Nome:");

        jTextFieldClienteCadastrarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteCadastrarNomeActionPerformed(evt);
            }
        });

        jLabelCadastroClienteCodigo.setText("Código:");

        jLabelCadastroClienteCPF.setText("CPF:");

        jLabelCadastroClienteEmail.setText("E-Mail:");

        jLabelCadastroClienteSenha.setText("Senha:");

        jLabelCadastroClienteEndereco1.setText("Endereço:");

        jLabelCadastroClienteEnderecoOpcional.setText("Endereços Adicionais(Opcional)");

        jLabelCadastroClienteEndereco2.setText("Endereço:");

        jLabelCadastroClienteEndereco3.setText("Endereço:");

        jButtonClienteCadastrar.setText("Cadastrar");
        jButtonClienteCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClienteCadastrarMouseClicked(evt);
            }
        });
        jButtonClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClienteCadastrarLayout = new javax.swing.GroupLayout(jPanelClienteCadastrar);
        jPanelClienteCadastrar.setLayout(jPanelClienteCadastrarLayout);
        jPanelClienteCadastrarLayout.setHorizontalGroup(
            jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                            .addComponent(jLabelCadastroClienteEndereco1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldClienteCadastrarEndereco1))
                        .addComponent(jLabelCadastroClienteEnderecoOpcional)
                        .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                            .addComponent(jLabelCadastroClienteEndereco2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldClienteCadastrarEndereco2))
                        .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                            .addComponent(jLabelCadastroClienteEndereco3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldClienteCadastrarEndereco3))
                        .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                            .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelClienteCadastrarLayout.createSequentialGroup()
                                    .addComponent(jLabelCadastroClienteSenha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPasswordFieldCadastrarSenha))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelClienteCadastrarLayout.createSequentialGroup()
                                    .addComponent(jLabelCadastroClienteCPF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldClienteCadastrarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelCadastroClienteEmail)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldClienteCadastrarEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                        .addComponent(jLabelCadastroClienteNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldClienteCadastrarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCadastroClienteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldClienteCadastrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteCadastrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClienteCadastrar)
                .addContainerGap())
        );
        jPanelClienteCadastrarLayout.setVerticalGroup(
            jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroClienteNome)
                    .addComponent(jTextFieldClienteCadastrarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroClienteCodigo)
                    .addComponent(jTextFieldClienteCadastrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroClienteCPF)
                    .addComponent(jTextFieldClienteCadastrarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroClienteEmail)
                    .addComponent(jTextFieldClienteCadastrarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroClienteSenha)
                    .addComponent(jPasswordFieldCadastrarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroClienteEndereco1)
                    .addComponent(jTextFieldClienteCadastrarEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCadastroClienteEnderecoOpcional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroClienteEndereco2)
                    .addComponent(jTextFieldClienteCadastrarEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroClienteEndereco3)
                    .addComponent(jTextFieldClienteCadastrarEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButtonClienteCadastrar)
                .addContainerGap())
        );

        jTabbedPaneCliente.addTab("Cadastrar Cliente", jPanelClienteCadastrar);

        jLabelClienteAlterarCodigo.setText("Código:");

        jTextFieldClienteAlterarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteAlterarCodigoActionPerformed(evt);
            }
        });

        jLabelClienteAlterarNome.setText("Novo nome:");

        jLabelClienteAlterarCPF.setText("Novo CPF:");

        jLabelClienteAlterarEmail.setText("Novo e-mail:");

        jLabelClienteAlterarEndereco.setText("Novo endereço:");

        jLabelClienteAlterarSenha.setText("Nova senha:");

        jPasswordFieldClienteAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldClienteAlterarSenhaActionPerformed(evt);
            }
        });

        jButtonClienteAlterar.setText("Salvar Alterações");
        jButtonClienteAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClienteAlterarMouseClicked(evt);
            }
        });
        jButtonClienteAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteAlterarActionPerformed(evt);
            }
        });

        jLabelClienteAlterarCadastroAviso1.setForeground(new java.awt.Color(200, 2, 2));
        jLabelClienteAlterarCadastroAviso1.setText("*Obrigatório preencher");

        jLabelClienteAlterarCadastroAviso2.setForeground(new java.awt.Color(200, 2, 2));
        jLabelClienteAlterarCadastroAviso2.setText("*Obrigatório preencher");

        javax.swing.GroupLayout jPanelClienteAlterarLayout = new javax.swing.GroupLayout(jPanelClienteAlterar);
        jPanelClienteAlterar.setLayout(jPanelClienteAlterarLayout);
        jPanelClienteAlterarLayout.setHorizontalGroup(
            jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelClienteAlterarCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldClienteAlterarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelClienteAlterarCadastroAviso1))
                    .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelClienteAlterarNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldClienteAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelClienteAlterarCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldClienteAlterarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelClienteAlterarEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldClienteAlterarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelClienteAlterarSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldClienteAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelClienteAlterarCadastroAviso2))
                    .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelClienteAlterarEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldClienteAlterarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteAlterarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClienteAlterar)
                .addContainerGap())
        );
        jPanelClienteAlterarLayout.setVerticalGroup(
            jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteAlterarCodigo)
                    .addComponent(jTextFieldClienteAlterarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClienteAlterarCadastroAviso1))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteAlterarNome)
                    .addComponent(jTextFieldClienteAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteAlterarCPF)
                    .addComponent(jTextFieldClienteAlterarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteAlterarEmail)
                    .addComponent(jTextFieldClienteAlterarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteAlterarSenha)
                    .addComponent(jPasswordFieldClienteAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClienteAlterarCadastroAviso2))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteAlterarEndereco)
                    .addComponent(jTextFieldClienteAlterarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButtonClienteAlterar)
                .addContainerGap())
        );

        jTabbedPaneCliente.addTab("Alterar Cadastro", jPanelClienteAlterar);

        jButtonClienteListar.setText("Listar");
        jButtonClienteListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteListarActionPerformed(evt);
            }
        });

        jTextAreaListaClientes.setColumns(20);
        jTextAreaListaClientes.setRows(5);
        jScrollPaneListaClientes.setViewportView(jTextAreaListaClientes);

        javax.swing.GroupLayout jPanelClienteListarLayout = new javax.swing.GroupLayout(jPanelClienteListar);
        jPanelClienteListar.setLayout(jPanelClienteListarLayout);
        jPanelClienteListarLayout.setHorizontalGroup(
            jPanelClienteListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteListarLayout.createSequentialGroup()
                        .addGap(0, 423, Short.MAX_VALUE)
                        .addComponent(jButtonClienteListar))
                    .addComponent(jScrollPaneListaClientes))
                .addContainerGap())
        );
        jPanelClienteListarLayout.setVerticalGroup(
            jPanelClienteListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneListaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonClienteListar)
                .addContainerGap())
        );

        jTabbedPaneCliente.addTab("Listar Clientes", jPanelClienteListar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCliente)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCliente)
        );

        jTabbedPane1.addTab("Cliente", jPanel1);

        jLabelProdutoCadastrarCodigo.setText("Código:");

        jLabelProdutoCadastrarQuantidade.setText("Quantidade:");

        jTextFieldProdutoCadastrarQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoCadastrarQuantidadeActionPerformed(evt);
            }
        });

        jLabelProdutoCadastrarPreco.setText("Preço unitário:");

        jTextFieldProdutoCadastrarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoCadastrarPrecoActionPerformed(evt);
            }
        });

        jLabelProdutoCadastrarDescricao.setText("Descrição:");

        jLabelProdutoCadastrarCategoria.setText("Categoria:");

        jLabelProdutoCadastrarParticularidade.setText("Particularidade:");

        jButtonProdutoCadastrar.setText("Cadastrar");
        jButtonProdutoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoCadastrarActionPerformed(evt);
            }
        });

        jTextFieldProdutoCadastrarDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoCadastrarDescricaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProdutoCadastrarLayout = new javax.swing.GroupLayout(jPanelProdutoCadastrar);
        jPanelProdutoCadastrar.setLayout(jPanelProdutoCadastrarLayout);
        jPanelProdutoCadastrarLayout.setHorizontalGroup(
            jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutoCadastrarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonProdutoCadastrar))
                    .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                        .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoCadastrarParticularidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoCadastrarParticularidade, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoCadastrarCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoCadastrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelProdutoCadastrarQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoCadastrarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoCadastrarCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoCadastrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoCadastrarPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoCadastrarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoCadastrarDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoCadastrarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelProdutoCadastrarLayout.setVerticalGroup(
            jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoCadastrarCodigo)
                    .addComponent(jTextFieldProdutoCadastrarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProdutoCadastrarQuantidade)
                    .addComponent(jTextFieldProdutoCadastrarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoCadastrarPreco)
                    .addComponent(jTextFieldProdutoCadastrarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoCadastrarCategoria)
                    .addComponent(jTextFieldProdutoCadastrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoCadastrarParticularidade)
                    .addComponent(jTextFieldProdutoCadastrarParticularidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoCadastrarDescricao)
                    .addComponent(jTextFieldProdutoCadastrarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jButtonProdutoCadastrar)
                .addContainerGap())
        );

        jTabbedPaneProduto.addTab("Cadastrar Produto", jPanelProdutoCadastrar);

        jLabelProdutoAlterarCodigo.setText("Código:");

        jLabelProdutoAlterarQuantidade.setText("Nova quantidade:");

        jLabelProdutoAlterarPreco.setText("Novo Preço:");

        jLabelProdutoAlterarCategoria.setText("Nova Categoria:");

        jLabelProdutoAlterarParticularidade.setText("Nova Particularidade:");

        jLabelProdutoAlterarDescricao.setText("Nova Descrição:");

        jButtonProdutoAlterar.setText("Salvar alterações");
        jButtonProdutoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProdutoAlterarLayout = new javax.swing.GroupLayout(jPanelProdutoAlterar);
        jPanelProdutoAlterar.setLayout(jPanelProdutoAlterarLayout);
        jPanelProdutoAlterarLayout.setHorizontalGroup(
            jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutoAlterarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonProdutoAlterar))
                    .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                        .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoAlterarPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoAlterarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoAlterarCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoAlterarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                                    .addComponent(jLabelProdutoAlterarParticularidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldProdutoAlterarParticularidade))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProdutoAlterarLayout.createSequentialGroup()
                                    .addComponent(jLabelProdutoAlterarCodigo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldProdutoAlterarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelProdutoAlterarQuantidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldProdutoAlterarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                                .addComponent(jLabelProdutoAlterarDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldProdutoAlterarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelProdutoAlterarLayout.setVerticalGroup(
            jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoAlterarCodigo)
                    .addComponent(jTextFieldProdutoAlterarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProdutoAlterarQuantidade)
                    .addComponent(jTextFieldProdutoAlterarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldProdutoAlterarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProdutoAlterarPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoAlterarCategoria)
                    .addComponent(jTextFieldProdutoAlterarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoAlterarParticularidade)
                    .addComponent(jTextFieldProdutoAlterarParticularidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoAlterarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProdutoAlterarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jButtonProdutoAlterar)
                .addContainerGap())
        );

        jTabbedPaneProduto.addTab("Alterar Estoque", jPanelProdutoAlterar);

        jButton1ListarProdutos.setText("Listar");
        jButton1ListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ListarProdutosActionPerformed(evt);
            }
        });

        jTextAreaListarProdutos.setColumns(20);
        jTextAreaListarProdutos.setRows(5);
        jScrollPaneListarProdutos.setViewportView(jTextAreaListarProdutos);

        javax.swing.GroupLayout jPanelProdutoListarLayout = new javax.swing.GroupLayout(jPanelProdutoListar);
        jPanelProdutoListar.setLayout(jPanelProdutoListarLayout);
        jPanelProdutoListarLayout.setHorizontalGroup(
            jPanelProdutoListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutoListarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1ListarProdutos))
                    .addComponent(jScrollPaneListarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelProdutoListarLayout.setVerticalGroup(
            jPanelProdutoListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutoListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneListarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1ListarProdutos)
                .addContainerGap())
        );

        jTabbedPaneProduto.addTab("Listar Produtos", jPanelProdutoListar);

        jButtonProdutoFiltrar.setText("Filtrar");
        jButtonProdutoFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoFiltrarActionPerformed(evt);
            }
        });

        jTextAreaFiltrarProdutos.setColumns(20);
        jTextAreaFiltrarProdutos.setRows(5);
        jScrollPaneProdutoFiltrar.setViewportView(jTextAreaFiltrarProdutos);

        javax.swing.GroupLayout jPanelProdutoFiltrarLayout = new javax.swing.GroupLayout(jPanelProdutoFiltrar);
        jPanelProdutoFiltrar.setLayout(jPanelProdutoFiltrarLayout);
        jPanelProdutoFiltrarLayout.setHorizontalGroup(
            jPanelProdutoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoFiltrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneProdutoFiltrar)
                    .addGroup(jPanelProdutoFiltrarLayout.createSequentialGroup()
                        .addComponent(jTextFieldProdutoFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonProdutoFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 236, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelProdutoFiltrarLayout.setVerticalGroup(
            jPanelProdutoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoFiltrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProdutoFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProdutoFiltrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneProdutoFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneProduto.addTab("Filtrar Produtos", jPanelProdutoFiltrar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneProduto, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneProduto, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Produto", jPanel2);

        jLabelVendaCadastrarCodigoVenda.setText("Código de venda:");

        jTextFieldVendasCadastrarCodigoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVendasCadastrarCodigoVendaActionPerformed(evt);
            }
        });

        jLabelVendaCadastrarCodigoCliente.setText("Código do cliente:");

        jTextFieldVendasCadastrarCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVendasCadastrarCodigoClienteActionPerformed(evt);
            }
        });

        jLabelVendaCadastrarData.setText("Data:");

        jLabelVendaCadastrarStatus.setText("Status:");

        jLabelVendaCadastrarCodigoProduto.setText("Código produto:");

        jLabelVendaCadastrarQuantidade.setText("Quantidade:");

        jButtonVendaCadastrar.setText("Cadastrar venda");
        jButtonVendaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendaCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVendasNovaLayout = new javax.swing.GroupLayout(jPanelVendasNova);
        jPanelVendasNova.setLayout(jPanelVendasNovaLayout);
        jPanelVendasNovaLayout.setHorizontalGroup(
            jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendasNovaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVendaCadastrar)
                .addContainerGap())
            .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                        .addComponent(jLabelVendaCadastrarCodigoVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVendasCadastrarCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                        .addComponent(jLabelVendaCadastrarCodigoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVendasCadastrarCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                        .addComponent(jLabelVendaCadastrarStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVendasCadastrarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                        .addComponent(jLabelVendaCadastrarQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVendasCadastrarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                        .addComponent(jLabelVendaCadastrarData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVendasCadastrarData, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                        .addComponent(jLabelVendaCadastrarCodigoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVendasCadastrarCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(259, 275, Short.MAX_VALUE))
        );
        jPanelVendasNovaLayout.setVerticalGroup(
            jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasNovaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVendaCadastrarCodigoVenda)
                    .addComponent(jTextFieldVendasCadastrarCodigoVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVendaCadastrarCodigoCliente)
                    .addComponent(jTextFieldVendasCadastrarCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVendaCadastrarCodigoProduto)
                    .addComponent(jTextFieldVendasCadastrarCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVendasCadastrarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVendaCadastrarStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldVendasCadastrarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVendaCadastrarQuantidade))
                .addGap(9, 9, 9)
                .addGroup(jPanelVendasNovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVendaCadastrarData)
                    .addComponent(jTextFieldVendasCadastrarData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jButtonVendaCadastrar)
                .addContainerGap())
        );

        jTabbedPaneVendas.addTab("Nova Venda", jPanelVendasNova);

        jLabelVendaAlterarCodigoVenda.setText("Código da venda:");

        jLabelVendaAlterarStatus.setText("Novo status:");

        jButtonVendaAlterar.setText("Salvar alteração");
        jButtonVendaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendaAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVendasAlterarLayout = new javax.swing.GroupLayout(jPanelVendasAlterar);
        jPanelVendasAlterar.setLayout(jPanelVendasAlterarLayout);
        jPanelVendasAlterarLayout.setHorizontalGroup(
            jPanelVendasAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendasAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendasAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelVendaAlterarCodigoVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVendasAlterarCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendasAlterarLayout.createSequentialGroup()
                        .addComponent(jLabelVendaAlterarStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVendasAlterarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(324, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendasAlterarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVendaAlterar)
                .addContainerGap())
        );
        jPanelVendasAlterarLayout.setVerticalGroup(
            jPanelVendasAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendasAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVendaAlterarCodigoVenda)
                    .addComponent(jTextFieldVendasAlterarCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendasAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVendaAlterarStatus)
                    .addComponent(jTextFieldVendasAlterarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(jButtonVendaAlterar)
                .addContainerGap())
        );

        jTabbedPaneVendas.addTab("Alterar Status de Venda", jPanelVendasAlterar);

        jButtonListarVendas.setText("Listar");
        jButtonListarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarVendasActionPerformed(evt);
            }
        });

        jTextAreaListarVendas.setColumns(20);
        jTextAreaListarVendas.setRows(5);
        jScrollPaneListarVendas.setViewportView(jTextAreaListarVendas);

        javax.swing.GroupLayout jPanelVendasListarLayout = new javax.swing.GroupLayout(jPanelVendasListar);
        jPanelVendasListar.setLayout(jPanelVendasListarLayout);
        jPanelVendasListarLayout.setHorizontalGroup(
            jPanelVendasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendasListarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonListarVendas))
                    .addComponent(jScrollPaneListarVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelVendasListarLayout.setVerticalGroup(
            jPanelVendasListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendasListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneListarVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonListarVendas)
                .addContainerGap())
        );

        jTabbedPaneVendas.addTab("Listar Vendas", jPanelVendasListar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVendas)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVendas)
        );

        jTabbedPane1.addTab("Vendas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldClienteAlterarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteAlterarCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteAlterarCodigoActionPerformed

    private void jPasswordFieldClienteAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldClienteAlterarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldClienteAlterarSenhaActionPerformed

    private void jTextFieldClienteCadastrarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteCadastrarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteCadastrarNomeActionPerformed

    private void jTextFieldProdutoCadastrarQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoCadastrarQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoCadastrarQuantidadeActionPerformed

    private void jButtonProdutoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoCadastrarActionPerformed
        
        Produto Produto = new Produto();
        Produto.SetProduto(Integer.parseInt(jTextFieldProdutoCadastrarCodigo.getText()), Integer.parseInt(jTextFieldProdutoCadastrarQuantidade.getText()), Double.parseDouble(jTextFieldProdutoCadastrarPreco.getText()), jTextFieldProdutoCadastrarDescricao.getText(), jTextFieldProdutoCadastrarCategoria.getText(), jTextFieldProdutoCadastrarParticularidade.getText());
        Estoque.AdicionaItem(Produto);
        jTextFieldProdutoCadastrarCodigo.setText("");
        jTextFieldProdutoCadastrarQuantidade.setText("");
        jTextFieldProdutoCadastrarPreco.setText("");
        jTextFieldProdutoCadastrarDescricao.setText("");
        jTextFieldProdutoCadastrarCategoria.setText("");
        jTextFieldProdutoCadastrarParticularidade.setText("");
    }//GEN-LAST:event_jButtonProdutoCadastrarActionPerformed

    private void jTextFieldProdutoCadastrarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoCadastrarPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoCadastrarPrecoActionPerformed

    private void jButtonProdutoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoAlterarActionPerformed
        int Index = Estoque.ProcuraIndex(Integer.parseInt(jTextFieldProdutoAlterarCodigo.getText()));
        int Codigo = Integer.parseInt(jTextFieldProdutoAlterarCodigo.getText());
        int Quantidade;
        double preco;
        String Descricao;
        String Categoria;
        String Particularidade;
        
        if(jTextFieldProdutoAlterarQuantidade.getText().length()>0){
            Quantidade = Integer.parseInt(jTextFieldProdutoAlterarQuantidade.getText());
        }else{
            Quantidade = Estoque.GetProduto(Index).Get_Quantidade();
        }
        if(jTextFieldProdutoAlterarPreco.getText().length()>0){
            preco = Double.parseDouble(jTextFieldProdutoAlterarPreco.getText());
        }else{
            preco = Estoque.GetProduto(Index).Get_Preco();
        }
        if(jTextFieldProdutoAlterarDescricao.getText().length()>0){
            Descricao = jTextFieldProdutoAlterarDescricao.getText();
        }else{
            Descricao = Estoque.GetProduto(Index).Get_Descricao();
        }
        if(jTextFieldProdutoAlterarCategoria.getText().length()>0){
            Categoria = jTextFieldProdutoAlterarCategoria.getText();
        }else{
            Categoria = Estoque.GetProduto(Index).Get_Categoria();
        }
        if(jTextFieldProdutoAlterarParticularidade.getText().length()>0){
            Particularidade = jTextFieldProdutoAlterarParticularidade.getText();
        }else{
            Particularidade = Estoque.GetProduto(Index).Get_Particularidade();
        }
        Estoque.AlteraEstoque(Codigo, Quantidade, preco, Descricao, Categoria, Particularidade);
        jTextFieldProdutoAlterarCodigo.setText("");
        jTextFieldProdutoAlterarQuantidade.setText("");
        jTextFieldProdutoAlterarPreco.setText("");
        jTextFieldProdutoAlterarDescricao.setText("");
        jTextFieldProdutoAlterarCategoria.setText("");
        jTextFieldProdutoAlterarParticularidade.setText("");
    }//GEN-LAST:event_jButtonProdutoAlterarActionPerformed

    private void jTextFieldVendasCadastrarCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVendasCadastrarCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVendasCadastrarCodigoClienteActionPerformed

    private void jTextFieldVendasCadastrarCodigoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVendasCadastrarCodigoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVendasCadastrarCodigoVendaActionPerformed

    private void jButtonVendaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaAlterarActionPerformed
        int Codigo = Integer.parseInt(jTextFieldVendasAlterarCodigoVenda.getText());
        String Status = jTextFieldVendasAlterarStatus.getText();
        Banco_Vendas.AlteraStatusVenda(Codigo, Status);
        jTextFieldVendasAlterarCodigoVenda.setText("");
        jTextFieldVendasAlterarStatus.setText("");
    }//GEN-LAST:event_jButtonVendaAlterarActionPerformed

    private void jButtonClienteAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClienteAlterarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClienteAlterarMouseClicked
    
    private void jButtonClienteCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClienteCadastrarMouseClicked

    }//GEN-LAST:event_jButtonClienteCadastrarMouseClicked

    private void jButtonClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteCadastrarActionPerformed
       Cliente Cliente = new Cliente();
       Cliente.SetNomeCPF_Cliente(jTextFieldClienteCadastrarNome.getText(), jTextFieldClienteCadastrarCPF.getText());
       Cliente.SetCodigo(Integer.parseInt(jTextFieldClienteCadastrarCodigo.getText()));
       Cliente.SetEmail(jTextFieldClienteCadastrarEmail.getText());
       Cliente.SetSenha(Arrays.toString(jPasswordFieldCadastrarSenha.getPassword()));
       Cliente.AdicionaEndereco(jTextFieldClienteCadastrarEndereco1.getText());
       Cliente.AdicionaEndereco(jTextFieldClienteCadastrarEndereco2.getText());
       Cliente.AdicionaEndereco(jTextFieldClienteCadastrarEndereco3.getText());
       
       
        Banco_Clientes.AdicionaCliente(Cliente);
        
        
       jTextFieldClienteCadastrarNome.setText("");
       jTextFieldClienteCadastrarCPF.setText("");
       jTextFieldClienteCadastrarCodigo.setText("");    
       jTextFieldClienteCadastrarEmail.setText("");
       jPasswordFieldCadastrarSenha.setText("");
       jTextFieldClienteCadastrarEndereco1.setText("");
       jTextFieldClienteCadastrarEndereco2.setText("");
       jTextFieldClienteCadastrarEndereco3.setText("");
    }//GEN-LAST:event_jButtonClienteCadastrarActionPerformed

    private void jButtonClienteAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteAlterarActionPerformed
        String nome = new String();
        String cpf = new String();
        String email = new String();
        String endereco = new String();
        int index = 0;
        int Codigo = Integer.parseInt(jTextFieldClienteAlterarCodigo.getText());
  
        if(jTextFieldClienteAlterarNome.getText().length()>0){
            nome = jTextFieldClienteAlterarNome.getText();
        }else{
            index = Banco_Clientes.ProcuraIndex(Codigo); 
            nome = Banco_Clientes.GetBancoCliente(index).GetNome();
        }
        if(jTextFieldClienteAlterarCPF.getText().length()>0){
            cpf = jTextFieldClienteAlterarCPF.getText();
        }else{
            index = Banco_Clientes.ProcuraIndex(Codigo); 
            cpf = Banco_Clientes.GetBancoCliente(index).GetCPF();
        }
        if(jTextFieldClienteAlterarEmail.getText().length()>0){
            email = jTextFieldClienteAlterarEmail.getText();
        }else{
            index = Banco_Clientes.ProcuraIndex(Codigo); 
            email = Banco_Clientes.GetBancoCliente(index).GetEmail();
        }
        if(jTextFieldClienteAlterarEndereco.getText().length()>0){
            endereco = jTextFieldClienteAlterarEndereco.getText();
        }else{
            index = Banco_Clientes.ProcuraIndex(Codigo); 
            endereco = Banco_Clientes.GetBancoCliente(index).GetPrimeiroEndereco();
        }
        Banco_Clientes.AlteraCliente(Codigo, nome, cpf, email, jPasswordFieldClienteAlterarSenha.getPassword().toString(), endereco);
        
        jTextFieldClienteAlterarNome.setText("");
        jTextFieldClienteAlterarCPF.setText("");
        jTextFieldClienteAlterarCodigo.setText("");    
        jTextFieldClienteAlterarEmail.setText("");
        jPasswordFieldClienteAlterarSenha.setText("");
        jTextFieldClienteAlterarEndereco.setText("");
        
        
    }//GEN-LAST:event_jButtonClienteAlterarActionPerformed

    private void jButtonVendaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaCadastrarActionPerformed
        int CodigoVenda = Integer.parseInt(jTextFieldVendasCadastrarCodigoVenda.getText());
        int CodigoCliente = Integer.parseInt(jTextFieldVendasCadastrarCodigoCliente.getText());
        int CodigoProduto = Integer.parseInt(jTextFieldVendasCadastrarCodigoProduto.getText());
        int Quantidade = Integer.parseInt(jTextFieldVendasCadastrarQuantidade.getText());
        String Data = jTextFieldVendasCadastrarData.getText();
        String Status = jTextFieldVendasCadastrarStatus.getText();
        
        Venda Venda = new Venda(CodigoVenda,CodigoCliente, Data,Status);
        Banco_Vendas.AdicionaVenda(Venda, Banco_Clientes);
        Venda.SetProdutoVendido(CodigoProduto, Quantidade, Estoque);
        
        jTextFieldVendasCadastrarCodigoVenda.setText("");
        jTextFieldVendasCadastrarCodigoCliente.setText("");
        jTextFieldVendasCadastrarCodigoProduto.setText("");
        jTextFieldVendasCadastrarQuantidade.setText("");
        jTextFieldVendasCadastrarData.setText("");
        jTextFieldVendasCadastrarStatus.setText("");
    }//GEN-LAST:event_jButtonVendaCadastrarActionPerformed

    private void jButtonClienteListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteListarActionPerformed
        jTextAreaListaClientes.setText("");
        int i;
        int j;
        for(i = 0; i< Banco_Clientes.getListaClientes().size(); i++){
            jTextAreaListaClientes.append("Código : " + Banco_Clientes.getListaClientes().get(i).GetCodigo() + "\n");
            jTextAreaListaClientes.append("Nome : " + Banco_Clientes.getListaClientes().get(i).GetNome() + "\n");
            jTextAreaListaClientes.append("CPF : " + Banco_Clientes.getListaClientes().get(i).GetCPF() + "\n");
            jTextAreaListaClientes.append("E-Mail : " + Banco_Clientes.getListaClientes().get(i).GetEmail() + "\n");
            for(j = 0; j<Banco_Clientes.getListaClientes().get(i).getEnderecos().size();j++){
            jTextAreaListaClientes.append("Endereço : " + Banco_Clientes.getListaClientes().get(i).getEnderecos().get(j) + "\n");
            }
            jTextAreaListaClientes.append("------------------------------------------------------\n");
        }
        
        
        
        
    }//GEN-LAST:event_jButtonClienteListarActionPerformed

    private void jTextFieldProdutoCadastrarDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoCadastrarDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoCadastrarDescricaoActionPerformed

    private void jButton1ListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ListarProdutosActionPerformed
        jTextAreaListarProdutos.setText("");
        for(int i = 0; i< Estoque.getEstoque().size(); i++){
            jTextAreaListarProdutos.append("Codigo : " + Estoque.getEstoque().get(i).Get_Codigo() + "\n");
            jTextAreaListarProdutos.append("Descrição : " + Estoque.getEstoque().get(i).Get_Descricao() + "\n");
            jTextAreaListarProdutos.append("Preço : " + Estoque.getEstoque().get(i).Get_Preco() + "\n");
            jTextAreaListarProdutos.append("Quantidade : " + Estoque.getEstoque().get(i).Get_Quantidade() + "\n");
            jTextAreaListarProdutos.append("Categoria : " + Estoque.getEstoque().get(i).Get_Categoria() + "\n");
            jTextAreaListarProdutos.append("Particularidade : " + Estoque.getEstoque().get(i).Get_Particularidade() + "\n");
            jTextAreaListarProdutos.append("---------------------------------------------------------\n");
        }
         
    }//GEN-LAST:event_jButton1ListarProdutosActionPerformed

    private void jButtonListarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarVendasActionPerformed
        jTextAreaListarVendas.setText("");
        for(int i = 0; i< Banco_Vendas.getVendas().size(); i++){
            jTextAreaListarVendas.append("Codigo Venda : " + Banco_Vendas.getVendas().get(i).GetCodigoVenda() + "\n");
            jTextAreaListarVendas.append("Codigo Cliente : " + Banco_Vendas.getVendas().get(i).GetCodigoC() + "\n");
            jTextAreaListarVendas.append("Codigo Status : " + Banco_Vendas.getVendas().get(i).GetStatus() + "\n");
            jTextAreaListarVendas.append("Data : " + Banco_Vendas.getVendas().get(i).GetData() + "\n");
            jTextAreaListarVendas.append("---------------------------------------------------------\n");
        }
    }//GEN-LAST:event_jButtonListarVendasActionPerformed

    private void jButtonProdutoFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoFiltrarActionPerformed
        String nome = jTextFieldProdutoFiltrar.getText();
        jTextAreaFiltrarProdutos.setText("");
        for(int i = 0; i< Estoque.getEstoque().size(); i++){
            if(Estoque.getEstoque().get(i).Get_Descricao().contains(nome)){
                jTextAreaFiltrarProdutos.append("Codigo : " + Estoque.getEstoque().get(i).Get_Codigo() + "\n");
                jTextAreaFiltrarProdutos.append("Descrição : " + Estoque.getEstoque().get(i).Get_Descricao() + "\n");
                jTextAreaFiltrarProdutos.append("Preço : " + Estoque.getEstoque().get(i).Get_Preco() + "\n");
                jTextAreaFiltrarProdutos.append("Quantidade : " + Estoque.getEstoque().get(i).Get_Quantidade() + "\n");
                jTextAreaFiltrarProdutos.append("Categoria : " + Estoque.getEstoque().get(i).Get_Categoria() + "\n");
                jTextAreaFiltrarProdutos.append("Particularidade : " + Estoque.getEstoque().get(i).Get_Particularidade() + "\n");
                jTextAreaFiltrarProdutos.append("---------------------------------------------------------\n");
            }
            
        }
        
        jTextFieldProdutoFiltrar.setText("");
    }//GEN-LAST:event_jButtonProdutoFiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ListarProdutos;
    private javax.swing.JButton jButtonClienteAlterar;
    private javax.swing.JButton jButtonClienteCadastrar;
    private javax.swing.JButton jButtonClienteListar;
    private javax.swing.JButton jButtonListarVendas;
    private javax.swing.JButton jButtonProdutoAlterar;
    private javax.swing.JButton jButtonProdutoCadastrar;
    private javax.swing.JButton jButtonProdutoFiltrar;
    private javax.swing.JButton jButtonVendaAlterar;
    private javax.swing.JButton jButtonVendaCadastrar;
    private javax.swing.JLabel jLabelCadastroClienteCPF;
    private javax.swing.JLabel jLabelCadastroClienteCodigo;
    private javax.swing.JLabel jLabelCadastroClienteEmail;
    private javax.swing.JLabel jLabelCadastroClienteEndereco1;
    private javax.swing.JLabel jLabelCadastroClienteEndereco2;
    private javax.swing.JLabel jLabelCadastroClienteEndereco3;
    private javax.swing.JLabel jLabelCadastroClienteEnderecoOpcional;
    private javax.swing.JLabel jLabelCadastroClienteNome;
    private javax.swing.JLabel jLabelCadastroClienteSenha;
    private javax.swing.JLabel jLabelClienteAlterarCPF;
    private javax.swing.JLabel jLabelClienteAlterarCadastroAviso1;
    private javax.swing.JLabel jLabelClienteAlterarCadastroAviso2;
    private javax.swing.JLabel jLabelClienteAlterarCodigo;
    private javax.swing.JLabel jLabelClienteAlterarEmail;
    private javax.swing.JLabel jLabelClienteAlterarEndereco;
    private javax.swing.JLabel jLabelClienteAlterarNome;
    private javax.swing.JLabel jLabelClienteAlterarSenha;
    private javax.swing.JLabel jLabelProdutoAlterarCategoria;
    private javax.swing.JLabel jLabelProdutoAlterarCodigo;
    private javax.swing.JLabel jLabelProdutoAlterarDescricao;
    private javax.swing.JLabel jLabelProdutoAlterarParticularidade;
    private javax.swing.JLabel jLabelProdutoAlterarPreco;
    private javax.swing.JLabel jLabelProdutoAlterarQuantidade;
    private javax.swing.JLabel jLabelProdutoCadastrarCategoria;
    private javax.swing.JLabel jLabelProdutoCadastrarCodigo;
    private javax.swing.JLabel jLabelProdutoCadastrarDescricao;
    private javax.swing.JLabel jLabelProdutoCadastrarParticularidade;
    private javax.swing.JLabel jLabelProdutoCadastrarPreco;
    private javax.swing.JLabel jLabelProdutoCadastrarQuantidade;
    private javax.swing.JLabel jLabelVendaAlterarCodigoVenda;
    private javax.swing.JLabel jLabelVendaAlterarStatus;
    private javax.swing.JLabel jLabelVendaCadastrarCodigoCliente;
    private javax.swing.JLabel jLabelVendaCadastrarCodigoProduto;
    private javax.swing.JLabel jLabelVendaCadastrarCodigoVenda;
    private javax.swing.JLabel jLabelVendaCadastrarData;
    private javax.swing.JLabel jLabelVendaCadastrarQuantidade;
    private javax.swing.JLabel jLabelVendaCadastrarStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelClienteAlterar;
    private javax.swing.JPanel jPanelClienteCadastrar;
    private javax.swing.JPanel jPanelClienteListar;
    private javax.swing.JPanel jPanelProdutoAlterar;
    private javax.swing.JPanel jPanelProdutoCadastrar;
    private javax.swing.JPanel jPanelProdutoFiltrar;
    private javax.swing.JPanel jPanelProdutoListar;
    private javax.swing.JPanel jPanelVendasAlterar;
    private javax.swing.JPanel jPanelVendasListar;
    private javax.swing.JPanel jPanelVendasNova;
    private javax.swing.JPasswordField jPasswordFieldCadastrarSenha;
    private javax.swing.JPasswordField jPasswordFieldClienteAlterarSenha;
    private javax.swing.JScrollPane jScrollPaneListaClientes;
    private javax.swing.JScrollPane jScrollPaneListarProdutos;
    private javax.swing.JScrollPane jScrollPaneListarVendas;
    private javax.swing.JScrollPane jScrollPaneProdutoFiltrar;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPaneCliente;
    private javax.swing.JTabbedPane jTabbedPaneProduto;
    private javax.swing.JTabbedPane jTabbedPaneVendas;
    private javax.swing.JTextArea jTextAreaFiltrarProdutos;
    private javax.swing.JTextArea jTextAreaListaClientes;
    private javax.swing.JTextArea jTextAreaListarProdutos;
    private javax.swing.JTextArea jTextAreaListarVendas;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextFieldClienteAlterarCPF;
    private javax.swing.JTextField jTextFieldClienteAlterarCodigo;
    private javax.swing.JTextField jTextFieldClienteAlterarEmail;
    private javax.swing.JTextField jTextFieldClienteAlterarEndereco;
    private javax.swing.JTextField jTextFieldClienteAlterarNome;
    private javax.swing.JTextField jTextFieldClienteCadastrarCPF;
    private javax.swing.JTextField jTextFieldClienteCadastrarCodigo;
    private javax.swing.JTextField jTextFieldClienteCadastrarEmail;
    private javax.swing.JTextField jTextFieldClienteCadastrarEndereco1;
    private javax.swing.JTextField jTextFieldClienteCadastrarEndereco2;
    private javax.swing.JTextField jTextFieldClienteCadastrarEndereco3;
    private javax.swing.JTextField jTextFieldClienteCadastrarNome;
    private javax.swing.JTextField jTextFieldProdutoAlterarCategoria;
    private javax.swing.JTextField jTextFieldProdutoAlterarCodigo;
    private javax.swing.JTextField jTextFieldProdutoAlterarDescricao;
    private javax.swing.JTextField jTextFieldProdutoAlterarParticularidade;
    private javax.swing.JTextField jTextFieldProdutoAlterarPreco;
    private javax.swing.JTextField jTextFieldProdutoAlterarQuantidade;
    private javax.swing.JTextField jTextFieldProdutoCadastrarCategoria;
    private javax.swing.JTextField jTextFieldProdutoCadastrarCodigo;
    private javax.swing.JTextField jTextFieldProdutoCadastrarDescricao;
    private javax.swing.JTextField jTextFieldProdutoCadastrarParticularidade;
    private javax.swing.JTextField jTextFieldProdutoCadastrarPreco;
    private javax.swing.JTextField jTextFieldProdutoCadastrarQuantidade;
    private javax.swing.JTextField jTextFieldProdutoFiltrar;
    private javax.swing.JTextField jTextFieldVendasAlterarCodigoVenda;
    private javax.swing.JTextField jTextFieldVendasAlterarStatus;
    private javax.swing.JTextField jTextFieldVendasCadastrarCodigoCliente;
    private javax.swing.JTextField jTextFieldVendasCadastrarCodigoProduto;
    private javax.swing.JTextField jTextFieldVendasCadastrarCodigoVenda;
    private javax.swing.JFormattedTextField jTextFieldVendasCadastrarData;
    private javax.swing.JTextField jTextFieldVendasCadastrarQuantidade;
    private javax.swing.JTextField jTextFieldVendasCadastrarStatus;
    // End of variables declaration//GEN-END:variables
}
